### PR TITLE
Introduce scraper localization

### PR DESCRIPTION
**Pull request by kelson42**
Recreated from https://github.com/openzim/phet/pull/178

### CODE REVIEW

**Comment by kelson42** [comment]
After trying again, it seems that actually the scraper works fine if only part of the strings are available in `fr.json` (or any translation file). But I have discovered other problems:
* If a json is not valid, the process should die (it does not for the moment)
* ZIM metadata have been changed but are wrong.
image

**Comment by kelson42** [comment]
@pavel-karatsiuba I had a look again to that PR. Thank you for the fixes. Here a few things left to do:
* Please remove the "zim-creator", I want to keep that in one (english) version

All the rest looks good. But reviewing this PR, i came to the conclusion that we should use this PR to really improve slightly the sizes and position of the test for 
image
Here the logo is far too big (whould be only slightly bigger in height than the two lines, the title should be horizontally centered to the middle of the logo. Finally the subtitle is really too small.

and 
image

Here the white overlay seems far to big in width, the title should not be sticked to the top, overall margins should there, the description font size is too small and the text in the two button seems slightly too small as well.

Maybe you want to fix these last remarks in another PR, I would understand it, otherwise feel free to make the fix here.

Then we will be good to merge

**Comment by kelson42** [comment]
@abijeet @translatewiki @Nikerabbit Could you please support this repository (within the Kiwix project)?

**Comment by Nikerabbit** [comment]
Can you to create a task in our Phabricator following the instructions in https://translatewiki.net/wiki/Translating:New_project? We will look into it after the holidays.

**Comment by kelson42** [comment]
Made at https://phabricator.wikimedia.org/T326040

**Pull request merged**
