### PR TITLE
Remove inline Javascript

### PR DESCRIPTION
**Pull request by pavel-karatsiuba**
Javascript was moved from index.html to a separate file.

Fixes https://github.com/openzim/phet/issues/134

### CODE REVIEW

**Comment by kelson42** [comment]
@pavel-karatsiuba ready to review (if then, please put me in reviewer)? Otherwise please rewrite the history, no merge in the feature branch.

**Review by kelson42 — CHANGES_REQUESTED** [review]
It seems we still have inline javascript (it does not pass in Kiwix JS). I see at least:
```
<script id='ractive-template' type='text/html'>
```
on home page

**Comment by pavel-karatsiuba** [comment]
> It seems we still have inline javascript (it does not pass in Kiwix JS). I see at least:
> 
> ```
> <script id='ractive-template' type='text/html'>
> ```
> 
> on home page

This script was not dangerous for CSP. But I also moved it to a separated file.

**Comment by kelson42** [comment]
@Jaifroid We have removed all the inline JS, but this still does not load properly in Kiwix-JS. See https://www.dropbox.com/s/alfulridglnsxkv/phet_fr_2022-12.zim?dl=0. Another problem?

**Comment by kelson42** [comment]
@Jaifroid Actually it seems that my test was wrong (was testing with JQuery). Works fine. I will merge the PR and let me know if any other problem.

**Review by kelson42 — APPROVED** [review]

**Comment by Jaifroid** [comment]
Thank you, this helps with https://github.com/kiwix/kiwix-js/issues/865.

**Pull request merged**
