### PR TITLE
fonts aren't missed anymore

### LINKED ISSUE #40: zimwriterfs seems unable to find a few fonts
```
stderr: zimwriterfs: unable to open file at path: state/export/phet_cs_2017-12/fonts/fontawesome-webfont.eot
zimwriterfs: unable to open file at path: state/export/phet_cs_2017-12/fonts/fontawesome-webfont.woff
zimwriterfs: unable to open file at path: state/export/phet_cs_2017-12/fonts/fontawesome-webfont.ttf
zimwriterfs: unable to open file at path: state/export/phet_cs_2017-12/fonts/OpenSans-Light.ttf

```

### PR DESCRIPTION
**Pull request by midik**
Fixes #40

### CODE REVIEW

**Comment by kelson42** [comment]
@midik Not sure this is related to that PR, but `npm start` get stuck for me:
```
child process exited with code 0
Creating Zim file...
stdout: Visiting directory state/export/phet_da_2020-03

stdout: T:12; A:547; RA:1; CA:445; UA:101; FA:448; IA:83; C:86; CC:83; UC:3; WC:8

stdout: T:14; Generate cluster offsets

stdout: T:14; ResolveRedirectIndexes
Resolve redirect
T:14; Set article indexes
set index
T:14; Resolve mimetype

stdout: T:14; create title index

stdout: T:14; 549 title index created
T:14; 88 clusters created
T:14; fill header

stdout: T:14; write zimfile :

stdout: T:14;  write header
T:14;  write mimetype list
T:14;  write url prt list

stdout: T:14;  write title index

stdout: T:14;  write directory entries

stdout: T:14;  write cluster offset list

stdout: T:14;  write cluster data

stdout: T:15;  write checksum

stdout: T:15; finish

child process exited with code 0
Creating Zim file...
stdout: Visiting directory state/export/phet_nl_2020-03
```

**Comment by midik** [comment]
@kelson42 I'm trying to reproduce this now by running a full cycle on the remote server

**Comment by midik** [comment]
@kelson42 well, I spent some time trying to reproduce this on amazon ec2 with 2Gb, and I wasn't facing the bug you've reported above. However, I couldn't get `imagemin` stuff working on that ec2 instance (it produces files with zero length) but that's irrelevant both to the bug you've reported above and to this PR's changes.
As the step towards resolving this issue, I think we could re-queue the tasks by tabling this PR for a while.  That time, I can give progress to the task #50 by rewriting image processing logic - that would allow me to run complete cycle on the ec2 server (or wherever else).
Does that make sense?

**Comment by midik** [comment]
image
(just fyi...here's what I'm getting on ec2 despite that I have all libs setup on host debian)

**Pull request merged**
