### PR TITLE
Fix sim preview scaling

### LINKED ISSUE #36: Preview should be displayed in one screen
... I always have to scroll down to open the simulation. I think the screenshot and the buttons should be scalled to be all displayed on the screen - so no need to scroll.
screenshot from 2017-09-14 21-24-23

### PR DESCRIPTION
**Pull request by midik**
fixes #36

### CODE REVIEW

**Comment by midik** [comment]
> CodeFactor — 7 issues found.

please ignore this: I have fixed those within another PR #71

**Comment by kelson42** [comment]
@midik Is this PR ready? If "yes" please assign it to me (or merge it straight).

**Comment by midik** [comment]
@kelson42 please take a look what the buttons and description look now. It's ok in terms of look and feel ?

**Comment by kelson42** [comment]
@midik This is more a workaround than a solution, you just have secure that the buttons are visible, without scaling the image properly. Why not just securing the screenshot of the sim is properly full displayed on the screen and that we don't need any scrollbar?

**Comment by midik** [comment]
fixes in another branch (#102), I'm going to close this one.

**Pull request closed without merging**
