### PR TITLE
Languages etc

### LINKED ISSUE #1: Add documentation for config.json

### LINKED ISSUE #19: Autodetect list of available language
This would avoid to maintain the list manually.

### LINKED ISSUE #29: Use local (script) to sort thumbnail on homepage
Sort order of exercises: they're sorted by the English name of the exercise rather than in the local language, which I'd recommend instead.

### LINKED ISSUE #38: PHeT content in Russian please.
_From @julianharty on December 17, 2017 19:18_

A user recently gave the Chemistry and Physics simulations app 1 star as it doesn't include Russian. 
There seem to be around 50 of the HTML5 simulations available in Russian according to https://phet.colorado.edu/en/simulations/translated/ru so it'd be great to make these available for users who prefer Russian.

New review on Dec 17, 2017 at 10:18 AM GMT ★
_Что за бред, есть все языки кроме русского??!!!_

_Copied from original issue: kiwix/kiwix-android#333_

### LINKED ISSUE #66: Activity categories have vanished
We have now only "all".

### PR DESCRIPTION
**Pull request by midik**
Fixes #66
Fixes #38
Fixes #19
Fixes #29
Fixes #1

### CODE REVIEW

**Comment by kelson42** [comment]
@midik Thank you for the PR. Small remark: I prefer that people do a rebase than merging master in the feature branch. I know a lot of companies does that, but I prefer a proper rebase on master.

Bigger remark: it does not start at all for me:
```
$ npm start

> phetscraper@1.0.0 start /home/kelson/code/phet
> npm run setup && npm run get && npm run transform && npm run export


> phetscraper@1.0.0 setup /home/kelson/code/phet
> node steps/setup.js


> phetscraper@1.0.0 get /home/kelson/code/phet
> node --no-warnings node_modules/ts-node/dist/bin.js steps/get.ts


/home/kelson/code/phet/node_modules/ts-node/src/index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
steps/get.ts:160:21 - error TS2569: Type 'Set<{ id: string; title: string; }>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

160           data: [...new Set(data)]
                        ~~~~~~~~~~~~~

    at createTSError (/home/kelson/code/phet/node_modules/ts-node/src/index.ts:421:12)
    at reportTSError (/home/kelson/code/phet/node_modules/ts-node/src/index.ts:425:19)
    at getOutput (/home/kelson/code/phet/node_modules/ts-node/src/index.ts:557:36)
    at Object.compile (/home/kelson/code/phet/node_modules/ts-node/src/index.ts:762:32)
    at Module.m._compile (/home/kelson/code/phet/node_modules/ts-node/src/index.ts:841:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/kelson/code/phet/node_modules/ts-node/src/index.ts:844:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetscraper@1.0.0 get: `node --no-warnings node_modules/ts-node/dist/bin.js steps/get.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 get script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kelson/.npm/_logs/2020-03-23T14_38_25_610Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetscraper@1.0.0 start: `npm run setup && npm run get && npm run transform && npm run export`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kelson/.npm/_logs/2020-03-23T14_38_25_628Z-debug.log
```

**Comment by midik** [comment]
> Bigger remark
fixed

**Comment by kelson42** [comment]
Now it runs, but I have far to few ZIM files generated:
```
$ ls -la dist/
total 348472
drwxr-xr-x  2 kelson kelson      4096 Mär 24 09:47 .
drwxr-xr-x 11 kelson kelson      4096 Mär 24 09:39 ..
-rw-r--r--  1 kelson kelson        70 Mär 23 16:31 .gitignore
-rw-r--r--  1 kelson kelson  22689318 Mär 24 09:43 phet_az_2020-03.zim
-rw-r--r--  1 kelson kelson  58979212 Mär 24 09:44 phet_en_2020-03.zim
-rw-r--r--  1 kelson kelson 167276857 Mär 24 09:47 phet_mul_2020-03.zim
-rw-r--r--  1 kelson kelson  56147274 Mär 24 09:44 phet_ru_2020-03.zim
-rw-r--r--  1 kelson kelson  51708810 Mär 24 09:45 phet_sv_2020-03.zim
```

**Comment by kelson42** [comment]
Looks good now :)

**Pull request merged**
