### PR TITLE
Fix/111/everything is broken

### PR DESCRIPTION
**Pull request by midik**

### CODE REVIEW

**Comment by kelson42** [comment]
@midik I don't know if this is ready as you don't have asked for review, but I tested and two times, the whole process (`npm i && npm start`) get stuck at:
```
2020-07-23 07:26:18 [info]: 	Gathering sim links... 
 ████████████████████████████████████████ 100% | ETA: 0s | 2555/211 | tr / wave-on-a-string
2020-07-23 07:32:22 [info]: 	Getting documents and images... 
 ███████████████████████░░░░░░░░░░░░░░░░░  57% | ETA: 2675s | 1504/2638 | wave-on-a-string_gl.html
```

**Comment by midik** [comment]
@kelson42 was there any warnings above?

**Comment by kelson42** [comment]
@midik Nothing

**Comment by midik** [comment]
@kelson42 could you please give it another try?

**Pull request merged**
